//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _001_Consumidor.ProxyCalculadora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCalculadora.ICalculadora")]
    public interface ICalculadora {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadora/Somar", ReplyAction="http://tempuri.org/ICalculadora/SomarResponse")]
        double Somar(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadora/Subtrair", ReplyAction="http://tempuri.org/ICalculadora/SubtrairResponse")]
        double Subtrair(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadora/Multiplicar", ReplyAction="http://tempuri.org/ICalculadora/MultiplicarResponse")]
        double Multiplicar(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadora/Dividir", ReplyAction="http://tempuri.org/ICalculadora/DividirResponse")]
        double Dividir(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculadora/Elevar", ReplyAction="http://tempuri.org/ICalculadora/ElevarResponse")]
        double Elevar(double x, double y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculadoraChannel : _001_Consumidor.ProxyCalculadora.ICalculadora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraClient : System.ServiceModel.ClientBase<_001_Consumidor.ProxyCalculadora.ICalculadora>, _001_Consumidor.ProxyCalculadora.ICalculadora {
        
        public CalculadoraClient() {
        }
        
        public CalculadoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Somar(double x, double y) {
            return base.Channel.Somar(x, y);
        }
        
        public double Subtrair(double x, double y) {
            return base.Channel.Subtrair(x, y);
        }
        
        public double Multiplicar(double x, double y) {
            return base.Channel.Multiplicar(x, y);
        }
        
        public double Dividir(double x, double y) {
            return base.Channel.Dividir(x, y);
        }
        
        public double Elevar(double x, double y) {
            return base.Channel.Elevar(x, y);
        }
    }
}
