//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace _001_MVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBEntities object using the connection string found in the 'DBEntities' section of the application configuration file.
        /// </summary>
        public DBEntities() : base("name=DBEntities", "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntities object.
        /// </summary>
        public DBEntities(string connectionString) : base(connectionString, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntities object.
        /// </summary>
        public DBEntities(EntityConnection connection) : base(connection, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pessoa> Pessoas
        {
            get
            {
                if ((_Pessoas == null))
                {
                    _Pessoas = base.CreateObjectSet<Pessoa>("Pessoas");
                }
                return _Pessoas;
            }
        }
        private ObjectSet<Pessoa> _Pessoas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pessoas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPessoas(Pessoa pessoa)
        {
            base.AddObject("Pessoas", pessoa);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="Pessoa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pessoa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pessoa object.
        /// </summary>
        /// <param name="cod">Initial value of the Cod property.</param>
        public static Pessoa CreatePessoa(global::System.Int32 cod)
        {
            Pessoa pessoa = new Pessoa();
            pessoa.Cod = cod;
            return pessoa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cod
        {
            get
            {
                return _Cod;
            }
            set
            {
                if (_Cod != value)
                {
                    OnCodChanging(value);
                    ReportPropertyChanging("Cod");
                    _Cod = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Cod");
                    OnCodChanged();
                }
            }
        }
        private global::System.Int32 _Cod;
        partial void OnCodChanging(global::System.Int32 value);
        partial void OnCodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.String _Sexo;
        partial void OnSexoChanging(global::System.String value);
        partial void OnSexoChanged();

        #endregion
    
    }

    #endregion
    
}
